---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: bcgov-baserow-configmap-dc
parameters:
  - description: The short-name of the BaseRow Service, lower-case with hyphen.
    displayName: BaseRow Acronym
    name: APP_NAME
    required: true
    value: test
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: "${APP_NAME}-baserow-configmap"
      labels:
        app: "${APP_NAME}-baserow"
    data:
      BASEROW_PUBLIC_URL: "http://${APP_NAME}-baserow:8000"
      WEB_FRONTEND_PORT: "8000"
      WEB_FRONTEND_SSL_PORT: "4443"
      MIGRATE_ON_STARTUP: "true"
      SYNC_TEMPLATES_ON_STARTUP: "true"
      PRIVATE_BACKEND_URL: "http://backend-asgi:8000"
      BASEROW_AMOUNT_OF_GUNICORN_WORKERS: "3"
      BASEROW_AMOUNT_OF_WORKERS: "1"      
      EMAIL_SMTP: "T"
      EMAIL_SMTP_HOST: "apps.smtp.gov.bc.ca"
      EMAIL_SMTP_PORT: "25"
      EMAIL_SMTP_USER: "Gary.T.Wong@gov.bc.ca"
      FROM_EMAIL: "Gary.T.Wong@gov.bc.ca"
      BASEROW_EXTRA_ALLOWED_HOSTS: "*"