---
kind: Template
apiVersion: template.openshift.io/v1
message: A new Baserow frontend application has been created in your project
metadata:
  name: bcgov-baserow-web-frontend
parameters:
  - description: The OpenShift Namespace where the ImageStream resides.
    displayName: ImageStream Namespace
    name: IS_NAMESPACE
    value: "acf456-tools"
  - description: Version of BaseRow app to be used (e.g. 1.13.3).
    displayName: Version of BaseRow
    name: BASEROW_TAG
    value: "1.13.3"    
  - description: The short-name of the Survey Service, lower-case with hyphen.
    displayName: BaseRow Acronym
    name: APP_NAME
    required: true
    value: "test"
  - name: CPU_LIMIT
    value: "200m"
  - name: MEMORY_LIMIT
    value: "512Mi"
  - name: CPU_REQUEST
    value: "50m"
  - name: MEMORY_REQUEST
    value: "200Mi"
objects:
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: "${APP_NAME}-baserow-web-frontend"
      generation: 1
      labels:
        app: "${APP_NAME}-baserow"
      annotations: {}
    spec:
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 600
          maxUnavailable: 25%
          maxSurge: 25%
        resources: {}
        activeDeadlineSeconds: 21600
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - "${APP_NAME}-baserow-web-frontend"
            from:
              kind: ImageStreamTag
              namespace: ${IS_NAMESPACE}
              name: bcgov-baserow-web-frontend:${BASEROW_TAG}
      replicas: 1
      revisionHistoryLimit: 10
      test: false
      selector:
        app: "${APP_NAME}-baserow"
        deploymentconfig: "${APP_NAME}-baserow-web-frontend"
      template:
        metadata:
          labels:
            app: "${APP_NAME}-baserow"
            deploymentconfig: "${APP_NAME}-baserow-web-frontend"
          annotations: {}
        spec:
          containers:
            - name: "${APP_NAME}-baserow-web-frontend"
              image: " "
              args:
              - nuxt         
              ports:
                - containerPort: 3000
                  protocol: TCP
              envFrom:
                - configMapRef:
                    name: "${APP_NAME}-baserow-configmap"                  
              env:
                - name: SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: "${APP_NAME}-baserow-secret"
                      key: secret-key
                - name: BASEROW_JWT_SIGNING_KEY
                  valueFrom:
                    secretKeyRef:
                      name: "${APP_NAME}-baserow-secret"
                      key: baserow-jwt-signing-key
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: "${APP_NAME}-baserow-redis"
                      key: redis-password
                - name: REDIS_HOST
                  value: "${APP_NAME}-baserow-redis"        
                # - name: DATABASE_USER
                #   valueFrom:
                #     secretKeyRef:
                #       name: "${APP_NAME}-baserow-postgresql"
                #       key: database-user
                # - name: DATABASE_PASSWORD
                #   valueFrom:
                #     secretKeyRef:
                #       name: "${APP_NAME}-baserow-postgresql"
                #       key: database-password
                # - name: DATABASE_NAME
                #   valueFrom:
                #     secretKeyRef:
                #       name: "${APP_NAME}-baserow-postgresql"
                #       key: database-name
                # - name: DATABASE_HOST
                #   value: "${APP_NAME}-baserow-postgresql"
                # - name: DATABASE_PORT
                #   value: "5432"
              resources:
                limits:
                  cpu: "${CPU_LIMIT}"
                  memory: "${MEMORY_LIMIT}"
                requests:
                  cpu: "${CPU_REQUEST}"
                  memory: "${MEMORY_REQUEST}"
              livenessProbe:
                tcpSocket:
                  port: 3000                    
                initialDelaySeconds: 60
                timeoutSeconds: 5
                periodSeconds: 30
                successThreshold: 1
                failureThreshold: 3
              readinessProbe:
                httpGet:
                  path: "/_health"
                  port: 3000
                  scheme: HTTP   
                initialDelaySeconds: 30
                timeoutSeconds: 5
                periodSeconds: 30
                successThreshold: 1
                failureThreshold: 10
              terminationMessagePath: "/dev/termination-log"
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${APP_NAME}-baserow-web-frontend"
      labels:
        app: "${APP_NAME}-baserow"
      annotations: {}
    spec:
      ports:
        - name: 8000-tcp
          protocol: TCP
          port: 8000
          targetPort: 3000
      selector:
        app: "${APP_NAME}-baserow"
        deploymentconfig: "${APP_NAME}-baserow-web-frontend"
      type: ClusterIP
      sessionAffinity: None
    status:
      loadBalancer: {}